title: Shark Blog
subtitle: Land of Sharks
description: Diving into the world of tech and beyond
author: Eddie Ho

# URL
url: http://example.com
root: /
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: false
titlecase: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Theme
theme: geek

# Search
search:
  path: search.json
  field: post

# code highlight
# prism_plugin:
#   mode: 'preprocess'    # realtime/preprocess
#   theme: 'ghcolors'
#   line_number: true    # default false

# deploy github
deploy:
  type: git
  repo: https://github.com/eddiehex/eddiehex.github.io.git
  branch: gh-pages

archive_generator:
  per_page: 0
  yearly: true
  monthly: true

highlight:
  enable: false
prismjs:
  enable: true

# Math rendering
math:
  engine: 'mathjax'
  mathjax:
    src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
    config:
      tex:
        inlineMath: [['$', '$'], ['\\(', '\\)']]
        displayMath: [['$$', '$$'], ['\\[', '\\]']]
        processEscapes: true

# 在适当的位置添加以下配置
# 如果已有 scripts 配置，只需添加新的路径
scripts:
  - /js/copy-code.js