- name: Temporary Image
  description: My personal Image bed
  icon: fas fa-upload
  url: https://bed.423327.xyz/

- name: Jupyter
  description: Online Jupyter-notebook
  icon: fas fa-book
  url: https://hexo.kygoho.win/py

- name: Alist
  description: My personal storage manager
  icon: fas fa-cloud
  url: https://alist.009100.xyz/

- name: RSS
  description: RSS online reader
  icon: fas fa-rss
  url: https://rss.009100.xyz

- name: Monitor
  description: Service Monitor Panel
  icon: fas fa-desktop
  url: https://cloud.kygoho.win/


- name: Image Hosting
  description: Image Hosting Service
  icon: fas fa-cloud-upload-alt
  url: https://up.423327.xyz

- name: Collection
  description: Collection of some sites
  icon: fas fa-folder
  url: https://charons.news